# this is the main workflow that is automatically triggered whenever there is a push or pull request to the main branch

name: OrgaNiUS

on:
  push:
    # change to main for both
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]
  workflow_dispatch: # for manually running this workflow

jobs:

  test-client:

    runs-on: ubuntu-latest

    steps:
    - run: echo "Testing client done here!"

  test-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.2'
    - uses: actions/checkout@v3
    - run: go test ./...

  deploy:

    # only run deploy step if merging into main
    # so, creating a PR will not run the deployment step
    if: github.ref == 'refs/heads/prod'
    # run deploy iff test stage passes
    needs: [ test-client, test-server ]

    runs-on: ubuntu-latest

    steps:
      # commented out the actual deploy for testing purposes
      - run: echo "Deploying to be done after test and only on merge"
    # Deploy to Heroku
#     - uses: actions/checkout@v2
#     - uses: akhileshns/heroku-deploy@v3.12.12
#       with:
#         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#         heroku_app_name: "organius"
#         heroku_email: ${{secrets.HEROKU_EMAIL}}
#         usedocker: true
